version: '3.4'
services:
  snowlabs:
    image: snowlabs-backend
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8008:8008
    env_file:
      - .env
